In [1]:
import pandas as pd
import numpy as np
import re
import pickle

import pandas as pd
from collections import Counter

from nltk.tokenize import sent_tokenize, word_tokenize, regexp_tokenize
from nltk.tokenize import regexp_tokenize
from nltk.corpus import stopwords

from nltk.stem import PorterStemmer, WordNetLemmatizer

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix

from datasets import Dataset
from transformers import DistilBertTokenizerFast, DistilBertForSequenceClassification
from transformers import TrainingArguments, Trainer

from peft import get_peft_model, LoraConfig, TaskType
import gensim
from gensim import corpora
from gensim.models.ldamulticore import LdaMulticore
import pyLDAvis.gensim_models
import pyLDAvis

import nltk
nltk.download('punkt')

import nltk
nltk.download('wordnet')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\lexil\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\lexil\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [2]:
lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

def preprocess(text_description):
    text_description = text_description.lower()
    text_description = text_description.translate(str.maketrans('', '', string.punctuation))
    tokens = word_tokenize(text_description)
    tokens = [lemmatizer.lemmatize(word) for word in tokens if word not in stop_words]
    return " ".join(tokens)

In [3]:
allbooksaddedprocessed = pd.read_csv('../data/allbooksaddedprocessed.csv')
allbooksaddedprocessed

,title,description,genre,published_date,authors,processed_description
0,the silver chair,two english children undergo hairraising adven...,fantasy,1998.0,clive staples lewis,two english child undergo hairraising adventur...
1,fablehaven,when kendra and seth go to stay at their grand...,fantasy,2007.0,brandon mull,kendra seth go stay grandparent estate discove...
2,a wizard of earthsea,originally published in 1968 ursula k le guins...,fantasy,2012.0,ursula k le guin,originally published 1968 ursula k le guins wi...
3,a game of thrones,fantasyroman,fantasy,1997.0,george r r martin,fantasyroman
4,keeper of the lost cities,at age 12 sophie learns that the remarkable ab...,fantasy,2012.0,shannon messenger,age 12 sophie learns remarkable ability always...
...,...,...,...,...,...,...
1409,by the gun,a collection of six western stories by an auth...,western,1993.0,richard matheson,collection six western story author specialize...
1410,die of gold,no description available,western,1992.0,chet cunningham,description available
1411,the sacking of el dorado,no description available,western,1994.0,max brand,description available
1412,the dakota deal,escaped prisoner john mccallums discovery of a...,western,2009.0,dan claymaker,escaped prisoner john mccallums discovery dese...
1413,larimont,john kendall didnt want to go back home to lar...,western,1999.0,will cade,john kendall didnt want go back home larimont ...

In [4]:
X = allbooksaddedprocessed['processed_description']
y = allbooksaddedprocessed['genre']

X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, test_size=0.2, random_state=42)

In [5]:
unigram_count_vectorizer = CountVectorizer()
unigram_model = make_pipeline(unigram_count_vectorizer, LogisticRegression(max_iter=1000))
unigram_model.fit(X_train, y_train)
y_pred_uni = unigram_model.predict(X_test)
print("Unigram Count Summary:\n", classification_report(y_test, y_pred_uni))
print(f'Accuracy: {accuracy_score(y_test, y_pred_uni)}')
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_uni))

bigram_count_vectorizer = CountVectorizer(ngram_range=(2, 2))
bigram_model = make_pipeline(bigram_count_vectorizer, LogisticRegression(max_iter=1000))
bigram_model.fit(X_train, y_train)
y_pred_bi = bigram_model.predict(X_test)
print("Bigram Count Summary:\n", classification_report(y_test, y_pred_bi))
print(f'Accuracy: {accuracy_score(y_test, y_pred_bi)}')
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_bi))

Unigram Count Summary:
                     precision    recall  f1-score   support

           fantasy       0.60      0.67      0.63        27
historical fiction       0.59      0.31      0.41        32
            horror       0.49      0.50      0.49        38
           mystery       0.43      0.36      0.39        33
           romance       0.41      0.57      0.48        37
   science fiction       0.94      0.89      0.91        36
          thriller       0.40      0.30      0.34        40
           western       0.54      0.72      0.62        40

          accuracy                           0.54       283
         macro avg       0.55      0.54      0.53       283
      weighted avg       0.55      0.54      0.53       283

Accuracy: 0.5406360424028268
Confusion Matrix:
 [[18  0  2  1  4  1  0  1]
 [ 1 10  3  2  8  0  5  3]
 [ 2  0 19  2  6  0  2  7]
 [ 4  1  3 12  2  1 10  0]
 [ 1  3  6  1 21  0  1  4]
 [ 1  0  0  2  0 32  0  1]
 [ 1  0  4  5  9  0 12  9]
 [ 2  3  2  3  1  0  0 29]]
Bigram Count Summary:
                     precision    recall  f1-score   support

           fantasy       0.25      0.07      0.11        27
historical fiction       0.33      0.03      0.06        32
            horror       0.24      0.32      0.27        38
           mystery       0.17      0.06      0.09        33
           romance       0.42      0.27      0.33        37
   science fiction       0.81      0.36      0.50        36
          thriller       0.50      0.10      0.17        40
           western       0.20      0.82      0.33        40

          accuracy                           0.27       283
         macro avg       0.37      0.25      0.23       283
      weighted avg       0.37      0.27      0.24       283

Accuracy: 0.27208480565371024
Confusion Matrix:
 [[ 2  0  8  1  2  1  0 13]
 [ 0  1  7  3  3  0  1 17]
 [ 0  0 12  1  2  0  0 23]
 [ 1  0  5  2  1  0  2 22]
 [ 0  1  6  1 10  0  0 19]
 [ 4  1  3  0  0 13  0 15]
 [ 1  0  4  4  6  1  4 20]
 [ 0  0  5  0  0  1  1 33]]

In [6]:
count_pipeline = make_pipeline(
    CountVectorizer(ngram_range=(1, 2)),  # unigrams and bigrams for count vect
    LogisticRegression(max_iter=1000)
)

param_grid = {
    'logisticregression__C': [0.01, 0.1, 1, 10, 100],
    'logisticregression__max_iter': [500, 1000, 1500]
}

grid_search = GridSearchCV(count_pipeline, param_grid, cv=5, scoring='accuracy', n_jobs=-1, verbose=2)

grid_search.fit(X_train, y_train)

best_count_pipeline = grid_search.best_estimator_

print("Best parameters:", grid_search.best_params_)
print("Best cross-validation accuracy:", grid_search.best_score_)

y_pred = grid_search.predict(X_test)
print("Test set classification report:\n", classification_report(y_test, y_pred))
print("Test set accuracy:", accuracy_score(y_test, y_pred))
print("Test set confusion matrix:\n", confusion_matrix(y_test, y_pred))

Fitting 5 folds for each of 15 candidates, totalling 75 fits
Best parameters: {'logisticregression__C': 1, 'logisticregression__max_iter': 500}
Best cross-validation accuracy: 0.5446805192780009
Test set classification report:
                     precision    recall  f1-score   support

           fantasy       0.55      0.67      0.60        27
historical fiction       0.56      0.28      0.38        32
            horror       0.44      0.50      0.47        38
           mystery       0.52      0.39      0.45        33
           romance       0.46      0.57      0.51        37
   science fiction       0.94      0.86      0.90        36
          thriller       0.43      0.30      0.35        40
           western       0.49      0.72      0.59        40

          accuracy                           0.54       283
         macro avg       0.55      0.54      0.53       283
      weighted avg       0.54      0.54      0.53       283

Test set accuracy: 0.5371024734982333
Test set confusion matrix:
 [[18  0  2  1  4  1  0  1]
 [ 3  9  3  2  7  0  4  4]
 [ 3  0 19  2  5  0  2  7]
 [ 3  0  4 13  2  0  9  2]
 [ 1  3  6  0 21  0  1  5]
 [ 2  1  0  2  0 31  0  0]
 [ 1  0  7  3  6  0 12 11]
 [ 2  3  2  2  1  1  0 29]]

In [7]:
vectorizer = best_count_pipeline.named_steps['countvectorizer']
classifier = best_count_pipeline.named_steps['logisticregression']

feature_names = vectorizer.get_feature_names_out()

num_top_features = 10  
class_labels = classifier.classes_

for i, class_label in enumerate(class_labels):
    coefs = classifier.coef_[i]
    top_indices = np.argsort(coefs)[-num_top_features:]
    print(f"\nTop features for class '{class_label}':")
    for idx in reversed(top_indices):
        print(f"  {feature_names[idx]}: {coefs[idx]:.4f}")

Top features for class 'fantasy':
  copy: 0.6988
  adventure: 0.6352
  publisher: 0.6325
  publisher description: 0.5846
  fantasy: 0.5342
  fantasyroman: 0.5114
  friend: 0.5064
  oz: 0.4893
  fantasy roman: 0.4812
  roman: 0.4778

Top features for class 'historical fiction':
  war: 0.8057
  dynastic saga: 0.6647
  dynastic: 0.6647
  saga: 0.6518
  love: 0.6383
  author: 0.6178
  life: 0.4972
  time: 0.4542
  trilogy: 0.4159
  jonathan lucas: 0.3925

Top features for class 'horror':
  horror: 1.2531
  description available: 0.7186
  nightmare: 0.6505
  thing: 0.6148
  evil: 0.5465
  power: 0.5354
  vampire: 0.5227
  tale: 0.5186
  science fictionroman: 0.5156
  fictionroman: 0.5156

Top features for class 'mystery':
  mystery: 1.0836
  murder: 0.9548
  nancy: 0.9449
  kriminalroman: 0.6979
  crime: 0.5562
  fantasyroman: 0.5126
  detective: 0.5110
  secret: 0.3909
  investigates: 0.3726
  york: 0.3683

Top features for class 'romance':
  love: 0.8378
  heart: 0.6688
  text: 0.5479
  romantic: 0.5227
  published: 0.5148
  heartwarming: 0.4773
  christmas story: 0.4414
  heartwarming christmas: 0.4414
  synopsis coming: 0.4405
  synopsis: 0.4333

Top features for class 'science fiction':
  fiction: 1.5173
  science: 0.8219
  list: 0.6914
  list member: 0.6231
  include: 0.6106
  vols: 0.5778
  member: 0.4977
  explores: 0.4876
  cyborg: 0.4646
  organism: 0.4620

Top features for class 'thriller':
  description available: 0.7595
  killer: 0.7439
  thriller: 0.7373
  available: 0.5972
  detective: 0.5818
  military: 0.5757
  description: 0.5667
  case: 0.5108
  murder: 0.4851
  medical: 0.4426

Top features for class 'western':
  western: 1.1894
  west: 1.1740
  description: 0.8857
  outlaw: 0.7050
  description available: 0.6854
  frontier: 0.6677
  man: 0.6073
  trail: 0.5821
  gang: 0.5771
  town: 0.5746

In [8]:
unigram_tfidf_vectorizer = TfidfVectorizer()
unigram_model = make_pipeline(unigram_tfidf_vectorizer, LogisticRegression(max_iter=1000))
unigram_model.fit(X_train, y_train)
y_pred_uni = unigram_model.predict(X_test)
print("Unigram TFIDF Summary:\n", classification_report(y_test, y_pred_uni))
print(f'Accuracy: {accuracy_score(y_test, y_pred_uni)}')
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_uni))

bigram_tfidf_vectorizer = TfidfVectorizer(ngram_range=(2, 2))
bigram_model = make_pipeline(bigram_tfidf_vectorizer, LogisticRegression(max_iter=1000))
bigram_model.fit(X_train, y_train)
y_pred_bi = bigram_model.predict(X_test)
print("Bigram TFIDF Summary:\n", classification_report(y_test, y_pred_bi))
print(f'Accuracy: {accuracy_score(y_test, y_pred_bi)}')
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_bi))

Unigram TFIDF Summary:
                     precision    recall  f1-score   support

           fantasy       0.85      0.41      0.55        27
historical fiction       0.57      0.41      0.47        32
            horror       0.58      0.50      0.54        38
           mystery       0.53      0.27      0.36        33
           romance       0.43      0.65      0.52        37
   science fiction       0.89      0.94      0.92        36
          thriller       0.39      0.47      0.43        40
           western       0.59      0.80      0.68        40

          accuracy                           0.57       283
         macro avg       0.60      0.56      0.56       283
      weighted avg       0.59      0.57      0.56       283

Accuracy: 0.568904593639576
Confusion Matrix:
 [[11  2  6  0  3  1  2  2]
 [ 0 13  2  2  9  0  4  2]
 [ 1  0 19  1  6  0  5  6]
 [ 1  0  2  9  4  2 15  0]
 [ 0  5  2  1 24  0  3  2]
 [ 0  0  1  0  0 34  0  1]
 [ 0  1  0  3  8  0 19  9]
 [ 0  2  1  1  2  1  1 32]]
Bigram TFIDF Summary:
                     precision    recall  f1-score   support

           fantasy       0.00      0.00      0.00        27
historical fiction       0.18      0.06      0.09        32
            horror       0.42      0.29      0.34        38
           mystery       0.58      0.21      0.31        33
           romance       0.37      0.51      0.43        37
   science fiction       0.66      0.58      0.62        36
          thriller       0.16      0.45      0.24        40
           western       0.50      0.45      0.47        40

          accuracy                           0.34       283
         macro avg       0.36      0.32      0.31       283
      weighted avg       0.37      0.34      0.33       283

Accuracy: 0.3392226148409894
Confusion Matrix:
 [[ 0  1  5  1  3  4 11  2]
 [ 0  2  3  1  4  1 19  2]
 [ 0  0 11  1  7  1 13  5]
 [ 1  0  3  7  4  2 15  1]
 [ 0  3  1  1 19  1 11  1]
 [ 1  2  1  0  2 21  9  0]
 [ 0  1  2  1 10  1 18  7]
 [ 0  2  0  0  2  1 17 18]]

In [9]:
tfidf_pipeline = make_pipeline(
    TfidfVectorizer(ngram_range=(1, 2)),  # unigrams and bigrams for tfidf
    LogisticRegression(max_iter=1000)
)

param_grid = {
    'logisticregression__C': [0.01, 0.1, 1, 10, 100],
    'logisticregression__max_iter': [500, 1000, 1500]
}

grid_search = GridSearchCV(tfidf_pipeline, param_grid, cv=5, scoring='accuracy', n_jobs=-1, verbose=2)

grid_search.fit(X_train, y_train)

best_count_pipeline = grid_search.best_estimator_

print("Best parameters:", grid_search.best_params_)
print("Best cross-validation accuracy:", grid_search.best_score_)

y_pred = grid_search.predict(X_test)
print("Test set classification report:\n", classification_report(y_test, y_pred))
print("Test set accuracy:", accuracy_score(y_test, y_pred))
print("Test set confusion matrix:\n", confusion_matrix(y_test, y_pred))

Fitting 5 folds for each of 15 candidates, totalling 75 fits
Best parameters: {'logisticregression__C': 100, 'logisticregression__max_iter': 500}
Best cross-validation accuracy: 0.5933257962652527
Test set classification report:
                     precision    recall  f1-score   support

           fantasy       0.74      0.52      0.61        27
historical fiction       0.50      0.53      0.52        32
            horror       0.63      0.50      0.56        38
           mystery       0.63      0.36      0.46        33
           romance       0.47      0.62      0.53        37
   science fiction       0.88      0.97      0.92        36
          thriller       0.37      0.38      0.37        40
           western       0.61      0.78      0.68        40

          accuracy                           0.59       283
         macro avg       0.60      0.58      0.58       283
      weighted avg       0.60      0.59      0.58       283

Test set accuracy: 0.5865724381625441
Test set confusion matrix:
 [[14  2  3  0  3  2  2  1]
 [ 0 17  1  1  6  1  4  2]
 [ 1  2 19  1  4  0  5  6]
 [ 1  1  3 12  2  0 13  1]
 [ 1  7  2  1 23  0  2  1]
 [ 1  0  0  0  0 35  0  0]
 [ 0  3  1  3  8  1 15  9]
 [ 1  2  1  1  3  1  0 31]]

In [10]:
vectorizer = best_count_pipeline.named_steps['tfidfvectorizer']
classifier = best_count_pipeline.named_steps['logisticregression']

feature_names = vectorizer.get_feature_names_out()

num_top_features = 10  
class_labels = classifier.classes_

for i, class_label in enumerate(class_labels):
    coefs = classifier.coef_[i]
    top_indices = np.argsort(coefs)[-num_top_features:]
    print(f"\nTop features for class '{class_label}':")
    for idx in reversed(top_indices):
        print(f"  {feature_names[idx]}: {coefs[idx]:.4f}")

Top features for class 'fantasy':
  copy: 4.5496
  oz: 4.4769
  adventure: 3.9081
  wizard: 3.8066
  fantasyroman: 3.5395
  magical: 3.2841
  eighteen science: 3.2500
  publisher description: 3.2292
  moomin: 3.1249
  eighteen: 3.0139

Top features for class 'historical fiction':
  war: 5.6215
  love: 4.6225
  life: 3.7410
  historical: 3.4524
  woman: 3.3632
  family: 3.1820
  author: 2.8743
  dynastic: 2.8289
  dynastic saga: 2.8289
  saga: 2.5752

Top features for class 'horror':
  horror: 9.0692
  nightmare: 3.8280
  vampire: 3.8145
  terrifying: 3.6686
  evil: 3.6146
  ghost: 3.3917
  thing: 3.1491
  poem: 3.0980
  science fictionroman: 2.9345
  fictionroman: 2.9345

Top features for class 'mystery':
  mystery: 6.7626
  nancy: 5.8498
  murder: 5.8014
  kriminalroman: 4.2350
  book: 4.0764
  fantasyroman: 3.1311
  crime: 3.0920
  detective: 3.0083
  inspector: 2.4363
  investigates: 2.4181

Top features for class 'romance':
  love: 6.1548
  heart: 4.2623
  bestselling: 2.9557
  romantic: 2.8767
  new york: 2.8559
  york: 2.8233
  wedding: 2.7804
  york time: 2.7606
  shes: 2.6512
  time bestselling: 2.6091

Top features for class 'science fiction':
  fiction: 10.9270
  science: 8.2131
  study: 3.8683
  literature: 3.8536
  climate: 3.2996
  form: 3.2741
  literary: 3.2489
  technology: 3.2045
  explores: 3.1689
  science fiction: 3.1298

Top features for class 'thriller':
  killer: 4.7636
  thriller: 4.6871
  case: 4.1749
  detective: 3.4685
  military: 2.8732
  murder: 2.6618
  medical: 2.6260
  victim: 2.5822
  key: 2.5820
  killing: 2.5365

Top features for class 'western':
  western: 6.9327
  west: 6.2071
  outlaw: 5.2521
  man: 4.1721
  frontier: 4.1619
  gang: 4.1409
  town: 4.1019
  indian: 3.5701
  gunfighter: 3.5359
  trail: 3.2117

In [11]:
allbooksaddedprocessed

,title,description,genre,published_date,authors,processed_description
0,the silver chair,two english children undergo hairraising adven...,fantasy,1998.0,clive staples lewis,two english child undergo hairraising adventur...
1,fablehaven,when kendra and seth go to stay at their grand...,fantasy,2007.0,brandon mull,kendra seth go stay grandparent estate discove...
2,a wizard of earthsea,originally published in 1968 ursula k le guins...,fantasy,2012.0,ursula k le guin,originally published 1968 ursula k le guins wi...
3,a game of thrones,fantasyroman,fantasy,1997.0,george r r martin,fantasyroman
4,keeper of the lost cities,at age 12 sophie learns that the remarkable ab...,fantasy,2012.0,shannon messenger,age 12 sophie learns remarkable ability always...
...,...,...,...,...,...,...
1409,by the gun,a collection of six western stories by an auth...,western,1993.0,richard matheson,collection six western story author specialize...
1410,die of gold,no description available,western,1992.0,chet cunningham,description available
1411,the sacking of el dorado,no description available,western,1994.0,max brand,description available
1412,the dakota deal,escaped prisoner john mccallums discovery of a...,western,2009.0,dan claymaker,escaped prisoner john mccallums discovery dese...
1413,larimont,john kendall didnt want to go back home to lar...,western,1999.0,will cade,john kendall didnt want go back home larimont ...

In [12]:
allbooksaddedprocessed = allbooksaddedprocessed.rename(columns={"processed_description": "text", "genre": "label"})
le = LabelEncoder()
allbooksaddedprocessed['label'] = le.fit_transform(allbooksaddedprocessed['label'])
allbooksaddedprocessed

,title,description,label,published_date,authors,text
0,the silver chair,two english children undergo hairraising adven...,0,1998.0,clive staples lewis,two english child undergo hairraising adventur...
1,fablehaven,when kendra and seth go to stay at their grand...,0,2007.0,brandon mull,kendra seth go stay grandparent estate discove...
2,a wizard of earthsea,originally published in 1968 ursula k le guins...,0,2012.0,ursula k le guin,originally published 1968 ursula k le guins wi...
3,a game of thrones,fantasyroman,0,1997.0,george r r martin,fantasyroman
4,keeper of the lost cities,at age 12 sophie learns that the remarkable ab...,0,2012.0,shannon messenger,age 12 sophie learns remarkable ability always...
...,...,...,...,...,...,...
1409,by the gun,a collection of six western stories by an auth...,7,1993.0,richard matheson,collection six western story author specialize...
1410,die of gold,no description available,7,1992.0,chet cunningham,description available
1411,the sacking of el dorado,no description available,7,1994.0,max brand,description available
1412,the dakota deal,escaped prisoner john mccallums discovery of a...,7,2009.0,dan claymaker,escaped prisoner john mccallums discovery dese...
1413,larimont,john kendall didnt want to go back home to lar...,7,1999.0,will cade,john kendall didnt want go back home larimont ...

In [13]:
num_labels = allbooksaddedprocessed['label'].nunique()
num_labels

8

In [14]:
dataset = Dataset.from_pandas(allbooksaddedprocessed)

In [15]:
dataset = dataset.train_test_split(test_size=0.2)

In [16]:
dataset['train']

Dataset({
    features: ['title', 'description', 'label', 'published_date', 'authors', 'text'],
    num_rows: 1131
})

In [17]:
train_dataset = dataset['train']
test_dataset = dataset['test']

In [18]:
tokenizer = DistilBertTokenizerFast.from_pretrained("distilbert-base-uncased")

In [19]:
train_dataset = train_dataset.map(lambda df: tokenizer(df['text'], padding="max_length", truncation=True), batched=True)
test_dataset = test_dataset.map(lambda df: tokenizer(df['text'], padding="max_length", truncation=True), batched=True)

Parameter 'function'=<function <lambda> at 0x000002494BC058A0> of the transform datasets.arrow_dataset.Dataset._map_single couldn't be hashed properly, a random hash was used instead. Make sure your transforms and parameters are serializable with pickle or dill for the dataset fingerprinting and caching to work. If you reuse this transform, the caching mechanism will consider it to be different from the previous calls and recompute everything. This warning is only showed once. Subsequent hashing failures won't be showed.

Map:   0%|          | 0/1131 [00:00<?, ? examples/s]

Map:   0%|          | 0/283 [00:00<?, ? examples/s]

In [20]:
train_dataset.set_format("torch", columns=["input_ids", "attention_mask", "label"])
test_dataset.set_format("torch", columns=["input_ids", "attention_mask", "label"])

In [21]:
model = DistilBertForSequenceClassification.from_pretrained("distilbert-base-uncased", num_labels=num_labels)

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [22]:
training = TrainingArguments(num_train_epochs = 5,
                  weight_decay = 0.01,
                  report_to = 'none')

In [23]:
training_object = Trainer(
    model = model,
    args = training,
    train_dataset = train_dataset
)

In [24]:
training_object.train()

c:\Users\lexil\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

c:\Users\lexil\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

TrainOutput(global_step=710, training_loss=0.6886369785792391, metrics={'train_runtime': 4953.229, 'train_samples_per_second': 1.142, 'train_steps_per_second': 0.143, 'total_flos': 749183294545920.0, 'train_loss': 0.6886369785792391, 'epoch': 5.0})

In [25]:
predicted = training_object.predict(test_dataset)

c:\Users\lexil\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

In [26]:
prediction_labels = predicted.predictions
true_labels = predicted.label_ids

In [27]:
preds = np.argmax(predicted.predictions, axis=-1)

In [28]:
#preds = le.inverse_transform(preds)
#preds

In [29]:
le.classes_

array(['fantasy', 'historical fiction', 'horror', 'mystery', 'romance',
       'science fiction', 'thriller', 'western'], dtype=object)

In [30]:
#model.save_pretrained("./model_trained")
model.save_pretrained("./model_added_trained")

In [31]:
#tokenizer.save_pretrained('./model_trained')
tokenizer.save_pretrained('./model_added_trained')

('./model_added_trained\\tokenizer_config.json',
 './model_added_trained\\special_tokens_map.json',
 './model_added_trained\\vocab.txt',
 './model_added_trained\\added_tokens.json',
 './model_added_trained\\tokenizer.json')

In [32]:
#from collections import Counter
#label_counts = Counter([example['label'] for example in train_dataset])
#label_counts = Counter([int(example['label']) for example in train_dataset])
#print(label_counts)

Doesn't look like class imbalances are an issue.

In [33]:
print("Test set classification report:\n", classification_report(true_labels, preds))
print("Test set accuracy:", accuracy_score(true_labels, preds))
print("Test set confusion matrix:\n", confusion_matrix(true_labels, preds))

Test set classification report:
               precision    recall  f1-score   support

           0       0.57      0.86      0.69        14
           1       0.52      0.57      0.54        30
           2       0.57      0.63      0.60        41
           3       0.53      0.44      0.48        36
           4       0.59      0.64      0.61        36
           5       0.92      0.94      0.93        35
           6       0.65      0.44      0.53        45
           7       0.81      0.83      0.82        46

    accuracy                           0.65       283
   macro avg       0.64      0.67      0.65       283
weighted avg       0.66      0.65      0.65       283

Test set accuracy: 0.6537102473498233
Test set confusion matrix:
 [[12  0  1  1  0  0  0  0]
 [ 2 17  2  1  6  1  0  1]
 [ 1  3 26  3  1  0  3  4]
 [ 0  5  3 16  4  1  6  1]
 [ 3  4  3  2 23  0  1  0]
 [ 1  0  0  0  1 33  0  0]
 [ 0  3  9  7  2  1 20  3]
 [ 2  1  2  0  2  0  1 38]]

In [34]:
correct_indices = np.where(preds == true_labels)[0]

# Pick a few examples (e.g., first 5 correct predictions)
num_examples = 5
sample_indices = correct_indices[:num_examples]

# Print texts with their predicted and true labels
for idx in sample_indices:
    print(f"Text: {test_dataset['text'][idx]}")
    print(f"True label: {le.inverse_transform([true_labels[idx]])[0]}")
    print(f"Predicted label: {le.inverse_transform([preds[idx]])[0]}")
    print('---')

Text: josey wale outlaw ride vast sunbaked land search place find peace jesus escobedo powerful cruel cross path josey wale meet force powerful good evilthe pure vengeance burn joseys heart
True label: western
Predicted label: western
---
Text: sleuthing monk unravels thorny case murder accomplished whodunit meticulously wrought wealth medieval detail booklist late spring 1142 brings dismay abbey saint peter saint paul may rose june 22 day young widow perle must receive one white rose rent house given benefit abbey contract void nature finally complies pious monk sent pay rentand found murdered beside hacked rosebush abbey wise herbalist brother cadfael follows trail bloodied petal know lovely widow dowry far greater house included likely wed cadfael ponder greedy suitor done dreadful deed another crime committed good monk must thread way tangle tortuous widow thorny bush
True label: historical fiction
Predicted label: historical fiction
---
Text: description available
True label: western
Predicted label: western
---
Text: father inherits old house town dark fall amanda josh exciteduntil begin suspect house haunted
True label: horror
Predicted label: horror
---
Text: novel set fictional town rosemary beach texas rancher fall love housemaid rock star father estate
True label: romance
Predicted label: romance
---

In [35]:
matches = (preds == true_labels)
print("Any correct predictions?", matches.any())
print("Number of correct predictions:", matches.sum())

Any correct predictions? True
Number of correct predictions: 185

In [36]:
print(confusion_matrix(true_labels, preds))
print(classification_report(true_labels, preds))

[[12  0  1  1  0  0  0  0]
 [ 2 17  2  1  6  1  0  1]
 [ 1  3 26  3  1  0  3  4]
 [ 0  5  3 16  4  1  6  1]
 [ 3  4  3  2 23  0  1  0]
 [ 1  0  0  0  1 33  0  0]
 [ 0  3  9  7  2  1 20  3]
 [ 2  1  2  0  2  0  1 38]]
              precision    recall  f1-score   support

           0       0.57      0.86      0.69        14
           1       0.52      0.57      0.54        30
           2       0.57      0.63      0.60        41
           3       0.53      0.44      0.48        36
           4       0.59      0.64      0.61        36
           5       0.92      0.94      0.93        35
           6       0.65      0.44      0.53        45
           7       0.81      0.83      0.82        46

    accuracy                           0.65       283
   macro avg       0.64      0.67      0.65       283
weighted avg       0.66      0.65      0.65       283

Fantasy - pretty strong, pretty distinct words. 
Historical fiction - worst performancce at 52% possible crossover with things like love, war, family  
Mystery - good, maybe crossover? (crime/love could be getting things mixed with romance or historical fiction perhaps.)
Romance - Good 
Sci-Fi  - best - likely because the vocabulary is pretty distinct?

Next steps - try getting more books? 
attempt to look at bi-grams 
topic modeling --  pi - LDA -vis
LoRA ?
Jaccard similarity between genres?

In [37]:
def preprocess(text):
    tokens = word_tokenize(text.lower())
    return [token for token in tokens if token.isalpha() and token not in stop_words]

allbooksprocessed['processed_text'] = allbooksprocessed['text'].apply(preprocess)

c:\Users\lexil\anaconda3\Lib\site-packages\executing\executing.py:713: DeprecationWarning: ast.Str is deprecated and will be removed in Python 3.14; use ast.Constant instead
  right=ast.Str(s=sentinel),
c:\Users\lexil\anaconda3\Lib\site-packages\executing\executing.py:713: DeprecationWarning: ast.Str is deprecated and will be removed in Python 3.14; use ast.Constant instead
  right=ast.Str(s=sentinel),
c:\Users\lexil\anaconda3\Lib\ast.py:587: DeprecationWarning: Attribute s is deprecated and will be removed in Python 3.14; use value instead
  return Constant(*args, **kwargs)
c:\Users\lexil\anaconda3\Lib\site-packages\executing\executing.py:713: DeprecationWarning: ast.Str is deprecated and will be removed in Python 3.14; use ast.Constant instead
  right=ast.Str(s=sentinel),
c:\Users\lexil\anaconda3\Lib\ast.py:587: DeprecationWarning: Attribute s is deprecated and will be removed in Python 3.14; use value instead
  return Constant(*args, **kwargs)
c:\Users\lexil\anaconda3\Lib\site-packages\executing\executing.py:713: DeprecationWarning: ast.Str is deprecated and will be removed in Python 3.14; use ast.Constant instead
  right=ast.Str(s=sentinel),
c:\Users\lexil\anaconda3\Lib\ast.py:587: DeprecationWarning: Attribute s is deprecated and will be removed in Python 3.14; use value instead
  return Constant(*args, **kwargs)
c:\Users\lexil\anaconda3\Lib\site-packages\executing\executing.py:713: DeprecationWarning: ast.Str is deprecated and will be removed in Python 3.14; use ast.Constant instead
  right=ast.Str(s=sentinel),
c:\Users\lexil\anaconda3\Lib\ast.py:587: DeprecationWarning: Attribute s is deprecated and will be removed in Python 3.14; use value instead
  return Constant(*args, **kwargs)

NameError: name 'allbooksprocessed' is not defined

In [ ]:
texts = allbooksprocessed['processed_text'].tolist()

dictionary = corpora.Dictionary(texts)
corpus = [dictionary.doc2bow(text) for text in texts]

In [ ]:
num_topics = 5 

lda_model = LdaMulticore(corpus, num_topics=num_topics, id2word=dictionary, passes=10, workers=2)

for idx, topic in lda_model.print_topics(num_topics):
    print(f"Topic {idx}: {topic}")

fantasy
historical fiction
mystery
romance
science fiction

In [ ]:
vis = pyLDAvis.gensim_models.prepare(lda_model, corpus, dictionary)

pyLDAvis.display(vis)

In [ ]:
print(vis.topic_info['Category'].tolist())

In [ ]:
from transformers import DistilBertTokenizerFast, DistilBertForSequenceClassification, Trainer, TrainingArguments
from datasets import load_dataset
import os

# Load data
dataset = load_dataset("ag_news", split="train[:1%]").train_test_split(test_size=0.2)
tokenizer = DistilBertTokenizerFast.from_pretrained("distilbert-base-uncased")
encoded = dataset.map(lambda x: tokenizer(x["text"], truncation=True, padding=True), batched=True)
encoded.set_format(type='torch', columns=['input_ids', 'attention_mask', 'label'])

# Load model with custom classification head
model = DistilBertForSequenceClassification.from_pretrained("distilbert-base-uncased", num_labels=4)

# Training args
args = TrainingArguments(
    output_dir="./saved_model",
    num_train_epochs=1,
    per_device_train_batch_size=8,
    logging_dir="./logs",
)

# Train
trainer = Trainer(model=model, args=args, train_dataset=encoded['train'], eval_dataset=encoded['test'])
trainer.train()
trainer.save_model("./saved_model")
tokenizer.save_pretrained("./saved_model")

print("Saved files:", os.listdir("./saved_model"))