In [1]:
import requests
import pandas as pd
import numpy as np

from llama_index.core import SimpleDirectoryReader

import re
import os
import json
import time
import ast
from collections import Counter
import string


from nltk.tokenize import sent_tokenize, word_tokenize, regexp_tokenize
from nltk.tokenize import regexp_tokenize
from nltk.corpus import stopwords

from nltk.stem import PorterStemmer, WordNetLemmatizer

import nltk
nltk.download('punkt')

import nltk
nltk.download('wordnet')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\lexil\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\lexil\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [2]:
os.getcwd()

'c:\\Users\\lexil\\Documents\\NSS_Projects\\Book_Blurb_Capstone\\notebooks'

In [3]:
with open('../data/fantasy_books_500.json', 'r') as file:
    fantasy = json.load(file)

pattern = re.compile(r'(\d{4})')

for book in fantasy:
    original_date = book.get('published_date', '')
    match = pattern.search(original_date)
    if match:
        book['published_date'] = match.group(1)
    else:
        book['published_date'] = original_date

In [4]:

def extract_year(date_str):
    match = re.search(r'\b(\d{4})\b', date_str)
    return match.group(1) if match else date_str 

for book in fantasy:
    book['published_date'] = extract_year(book['published_date'])


json_file_path = 'data/fantasy_books_500.json'

with open('../data/fantasy_books_500.json', 'w', encoding='utf-8') as f:
    json.dump(fantasy, f, ensure_ascii=False, indent=4)

In [5]:
with open('../data/historical_fiction_books_500.json', 'r') as file:
    historical_fiction = json.load(file)

pattern = re.compile(r'(\d{4})')

for book in historical_fiction:
    original_date = book.get('published_date', '')
    match = pattern.search(original_date)
    if match:
        book['published_date'] = match.group(1)
    else:
        book['published_date'] = original_date

def extract_year(date_str):
    match = re.search(r'\b(\d{4})\b', date_str)
    return match.group(1) if match else date_str 

for book in historical_fiction:
    book['published_date'] = extract_year(book['published_date'])


json_file_path = '../data/historical_fiction_books_500.json'

with open('../data/historical_fiction_books_500.json', 'w', encoding='utf-8') as f:
    json.dump(historical_fiction, f, ensure_ascii=False, indent=4)

In [6]:
with open('../data/mystery_books_500.json', 'r') as file:
    mystery = json.load(file)

pattern = re.compile(r'(\d{4})')

for book in mystery:
    original_date = book.get('published_date', '')
    match = pattern.search(original_date)
    if match:
        book['published_date'] = match.group(1)
    else:
        book['published_date'] = original_date

def extract_year(date_str):
    match = re.search(r'\b(\d{4})\b', date_str)
    return match.group(1) if match else date_str 

for book in mystery:
    book['published_date'] = extract_year(book['published_date'])


json_file_path = '../data/mystery_books_500.json'

with open('../data/mystery_books_500.json', 'w', encoding='utf-8') as f:
    json.dump(mystery, f, ensure_ascii=False, indent=4)

In [7]:
with open('../data/romance_books_500.json', 'r') as file:
    romance = json.load(file)

pattern = re.compile(r'(\d{4})')

for book in romance:
    original_date = book.get('published_date', '')
    match = pattern.search(original_date)
    if match:
        book['published_date'] = match.group(1)
    else:
        book['published_date'] = original_date

def extract_year(date_str):
    match = re.search(r'\b(\d{4})\b', date_str)
    return match.group(1) if match else date_str 

for book in romance:
    book['published_date'] = extract_year(book['published_date'])


json_file_path = '../data/romance_books_500.json'

with open('../data/romance_books_500.json', 'w', encoding='utf-8') as f:
    json.dump(romance, f, ensure_ascii=False, indent=4)

In [8]:
with open('../data/science_fiction_books_500.json', 'r') as file:
    science_fiction = json.load(file)

pattern = re.compile(r'(\d{4})')

for book in science_fiction:
    original_date = book.get('published_date', '')
    match = pattern.search(original_date)
    if match:
        book['published_date'] = match.group(1)
    else:
        book['published_date'] = original_date

def extract_year(date_str):
    match = re.search(r'\b(\d{4})\b', date_str)
    return match.group(1) if match else date_str 

for book in science_fiction:
    book['published_date'] = extract_year(book['published_date'])


json_file_path = '../data/science_fiction_books_500.json'

with open('../data/science_fiction_books_500.json', 'w', encoding='utf-8') as f:
    json.dump(science_fiction, f, ensure_ascii=False, indent=4)

In [9]:
with open('../data/horror.json', 'r') as file:
    horror = json.load(file)

pattern = re.compile(r'(\d{4})')

for book in horror:
    original_date = book.get('published_date', '')
    match = pattern.search(original_date)
    if match:
        book['published_date'] = match.group(1)
    else:
        book['published_date'] = original_date

def extract_year(date_str):
    match = re.search(r'\b(\d{4})\b', date_str)
    return match.group(1) if match else date_str 

for book in horror:
    book['published_date'] = extract_year(book['published_date'])


json_file_path = '../data/horror.json'

with open('../data/horror.json', 'w', encoding='utf-8') as f:
    json.dump(horror, f, ensure_ascii=False, indent=4)

In [10]:
with open('../data/thriller.json', 'r') as file:
    thriller = json.load(file)

pattern = re.compile(r'(\d{4})')

for book in thriller:
    original_date = book.get('published_date', '')
    match = pattern.search(original_date)
    if match:
        book['published_date'] = match.group(1)
    else:
        book['published_date'] = original_date

def extract_year(date_str):
    match = re.search(r'\b(\d{4})\b', date_str)
    return match.group(1) if match else date_str 

for book in thriller:
    book['published_date'] = extract_year(book['published_date'])


json_file_path = '../data/thriller.json'

with open('../data/thriller.json', 'w', encoding='utf-8') as f:
    json.dump(thriller, f, ensure_ascii=False, indent=4)

In [11]:
with open('../data/western.json', 'r') as file:
    western = json.load(file)

pattern = re.compile(r'(\d{4})')

for book in western:
    original_date = book.get('published_date', '')
    match = pattern.search(original_date)
    if match:
        book['published_date'] = match.group(1)
    else:
        book['published_date'] = original_date

def extract_year(date_str):
    match = re.search(r'\b(\d{4})\b', date_str)
    return match.group(1) if match else date_str 

for book in western:
    book['published_date'] = extract_year(book['published_date'])


json_file_path = '../data/western.json'

with open('../data/western.json', 'w', encoding='utf-8') as f:
    json.dump(western, f, ensure_ascii=False, indent=4)

In [12]:
os.getcwd()

'c:\\Users\\lexil\\Documents\\NSS_Projects\\Book_Blurb_Capstone\\notebooks'

In [13]:
genre_files = {
    'Fantasy': '../data/fantasy_books_500.json',
    'Historical Fiction': '../data/historical_fiction_books_500.json',
    'Mystery': '../data/mystery_books_500.json',
    'Romance': '../data/romance_books_500.json',
    'Science Fiction': '../data/science_fiction_books_500.json',
    'Horror': '../data/horror.json',
    'Thriller': '../data/thriller.json',
    'Western': '../data/western.json'
}

all_books_with_adds = []

for genre, file_name in genre_files.items():
    with open(file_name, 'r', encoding='utf-8') as f:
        books = json.load(f)
        for book in books:
            book['genre'] = genre
        all_books_with_adds.extend(books)

with open('../data/all_books_with_adds.json', 'w', encoding='utf-8') as f:
    json.dump(all_books_with_adds, f, ensure_ascii=False, indent=4)

In [14]:
with open('../data/all_books_with_adds.json', 'r') as file:
    all_books_with_adds = json.load(file)

In [15]:
all_books_df = pd.DataFrame(all_books)
all_books_df

NameError: name 'all_books' is not defined

In [16]:
all_books_with_adds_df = pd.DataFrame(all_books_with_adds)
all_books_with_adds_df

,title,description,genre,published_date,authors
0,The Silver Chair,Two English children undergo hair-raising adve...,Fantasy,1998,[Clive Staples Lewis]
1,Fablehaven,When Kendra and Seth go to stay at their grand...,Fantasy,2007,[Brandon Mull]
2,A Wizard of Earthsea,"Originally published in 1968, Ursula K. Le Gui...",Fantasy,2012,[Ursula K. Le Guin]
3,A Game of Thrones,Fantasy-roman.,Fantasy,1997,[George R. R. Martin]
4,Keeper of the Lost Cities,"At age 12, Sophie learns that the remarkable a...",Fantasy,2012,[Shannon Messenger]
...,...,...,...,...,...
1409,By the Gun,A collection of six Western stories by an auth...,Western,1993,[Richard Matheson]
1410,Die of Gold,No description available.,Western,1992,[Chet Cunningham]
1411,The Sacking of El Dorado,No description available.,Western,1994,[Max Brand]
1412,The Dakota Deal,Escaped prisoner John McCallum's discovery of ...,Western,2009,[Dan Claymaker]
1413,Larimont,John Kendall didn't want to go back home to La...,Western,1999,[Will Cade]

In [ ]:
all_books_df.astype(str)
all_books_df['published_date'] = pd.to_numeric(all_books_df['published_date'], errors='coerce')

NameError: name 'all_books_df' is not defined

In [17]:
all_books_with_adds_df.astype(str)
all_books_with_adds_df['published_date'] = pd.to_numeric(all_books_with_adds_df['published_date'], errors='coerce')

In [18]:
all_books_with_adds_df['authors']

0       [Clive Staples Lewis]
1              [Brandon Mull]
2         [Ursula K. Le Guin]
3       [George R. R. Martin]
4         [Shannon Messenger]
                ...
1409       [Richard Matheson]
1410        [Chet Cunningham]
1411              [Max Brand]
1412          [Dan Claymaker]
1413              [Will Cade]
Name: authors, Length: 1414, dtype: object

In [19]:
all_books_with_adds_df.dtypes

title              object
description        object
genre              object
published_date    float64
authors            object
dtype: object

In [20]:
all_books_with_adds_df['authors'] = all_books_with_adds_df['authors'].apply(lambda x: ', '.join(x).lower() if isinstance(x, list) else '')
all_books_with_adds_df['authors']

0       clive staples lewis
1              brandon mull
2         ursula k. le guin
3       george r. r. martin
4         shannon messenger
               ...
1409       richard matheson
1410        chet cunningham
1411              max brand
1412          dan claymaker
1413              will cade
Name: authors, Length: 1414, dtype: object

In [21]:
all_books_with_adds_df[all_books_with_adds_df.select_dtypes(include = 'object').columns] = all_books_with_adds_df.select_dtypes(include = 'object').apply(lambda x: x.str.lower())
all_books_with_adds_df

,title,description,genre,published_date,authors
0,the silver chair,two english children undergo hair-raising adve...,fantasy,1998.0,clive staples lewis
1,fablehaven,when kendra and seth go to stay at their grand...,fantasy,2007.0,brandon mull
2,a wizard of earthsea,"originally published in 1968, ursula k. le gui...",fantasy,2012.0,ursula k. le guin
3,a game of thrones,fantasy-roman.,fantasy,1997.0,george r. r. martin
4,keeper of the lost cities,"at age 12, sophie learns that the remarkable a...",fantasy,2012.0,shannon messenger
...,...,...,...,...,...
1409,by the gun,a collection of six western stories by an auth...,western,1993.0,richard matheson
1410,die of gold,no description available.,western,1992.0,chet cunningham
1411,the sacking of el dorado,no description available.,western,1994.0,max brand
1412,the dakota deal,escaped prisoner john mccallum's discovery of ...,western,2009.0,dan claymaker
1413,larimont,john kendall didn't want to go back home to la...,western,1999.0,will cade

In [22]:
all_books_with_adds_df['title'] = all_books_with_adds_df['title'].str.replace(r'[^\w\s]', '', regex=True)
all_books_with_adds_df

,title,description,genre,published_date,authors
0,the silver chair,two english children undergo hair-raising adve...,fantasy,1998.0,clive staples lewis
1,fablehaven,when kendra and seth go to stay at their grand...,fantasy,2007.0,brandon mull
2,a wizard of earthsea,"originally published in 1968, ursula k. le gui...",fantasy,2012.0,ursula k. le guin
3,a game of thrones,fantasy-roman.,fantasy,1997.0,george r. r. martin
4,keeper of the lost cities,"at age 12, sophie learns that the remarkable a...",fantasy,2012.0,shannon messenger
...,...,...,...,...,...
1409,by the gun,a collection of six western stories by an auth...,western,1993.0,richard matheson
1410,die of gold,no description available.,western,1992.0,chet cunningham
1411,the sacking of el dorado,no description available.,western,1994.0,max brand
1412,the dakota deal,escaped prisoner john mccallum's discovery of ...,western,2009.0,dan claymaker
1413,larimont,john kendall didn't want to go back home to la...,western,1999.0,will cade

In [23]:
all_books_with_adds_df['description'] = all_books_with_adds_df['description'].str.replace(r'[^\w\s]', '', regex=True)
all_books_with_adds_df

,title,description,genre,published_date,authors
0,the silver chair,two english children undergo hairraising adven...,fantasy,1998.0,clive staples lewis
1,fablehaven,when kendra and seth go to stay at their grand...,fantasy,2007.0,brandon mull
2,a wizard of earthsea,originally published in 1968 ursula k le guins...,fantasy,2012.0,ursula k. le guin
3,a game of thrones,fantasyroman,fantasy,1997.0,george r. r. martin
4,keeper of the lost cities,at age 12 sophie learns that the remarkable ab...,fantasy,2012.0,shannon messenger
...,...,...,...,...,...
1409,by the gun,a collection of six western stories by an auth...,western,1993.0,richard matheson
1410,die of gold,no description available,western,1992.0,chet cunningham
1411,the sacking of el dorado,no description available,western,1994.0,max brand
1412,the dakota deal,escaped prisoner john mccallums discovery of a...,western,2009.0,dan claymaker
1413,larimont,john kendall didnt want to go back home to lar...,western,1999.0,will cade

In [24]:
all_books_with_adds_df['authors'] = all_books_with_adds_df['authors'].str.replace(r'[^\w\s]', '', regex=True)
all_books_with_adds_df

,title,description,genre,published_date,authors
0,the silver chair,two english children undergo hairraising adven...,fantasy,1998.0,clive staples lewis
1,fablehaven,when kendra and seth go to stay at their grand...,fantasy,2007.0,brandon mull
2,a wizard of earthsea,originally published in 1968 ursula k le guins...,fantasy,2012.0,ursula k le guin
3,a game of thrones,fantasyroman,fantasy,1997.0,george r r martin
4,keeper of the lost cities,at age 12 sophie learns that the remarkable ab...,fantasy,2012.0,shannon messenger
...,...,...,...,...,...
1409,by the gun,a collection of six western stories by an auth...,western,1993.0,richard matheson
1410,die of gold,no description available,western,1992.0,chet cunningham
1411,the sacking of el dorado,no description available,western,1994.0,max brand
1412,the dakota deal,escaped prisoner john mccallums discovery of a...,western,2009.0,dan claymaker
1413,larimont,john kendall didnt want to go back home to lar...,western,1999.0,will cade

In [25]:
all_books_with_adds_df['genre'].unique()

array(['fantasy', 'historical fiction', 'mystery', 'romance',
       'science fiction', 'horror', 'thriller', 'western'], dtype=object)

In [32]:
type(all_books_with_adds_df)

pandas.core.frame.DataFrame

In [36]:
all_books_with_adds_df.to_csv('../data/allbooksaddednormalized.csv')

In [28]:
import os
os.getcwd()

'c:\\Users\\lexil\\Documents\\NSS_Projects\\Book_Blurb_Capstone\\notebooks'

In [38]:
all_books_added_normalized = pd.read_csv('../data/allbooksaddednormalized.csv', index_col=0)
all_books_added_normalized.head()
len(all_books_added_normalized)

1414

In [39]:
all_books_added_normalized.dropna(subset=['genre', 'description'], inplace=True)
len(all_books_added_normalized)

1414

In [40]:
lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

In [42]:
def preprocess(text_description):
    text_description = text_description.lower()
    text_description = text_description.translate(str.maketrans('', '', string.punctuation))
    tokens = word_tokenize(text_description)
    tokens = [lemmatizer.lemmatize(word) for word in tokens if word not in stop_words]
    return " ".join(tokens)
all_books_added_normalized['processed_description'] = all_books_added_normalized['description'].apply(preprocess)

In [ ]:
all_books_df

In [ ]:
all_books_df.to_csv('../data/allbooksprocessed.csv', index = False)

In [43]:
all_books_added_normalized.to_csv('../data/allbooksaddedprocessed.csv', index = False)